### ISSUE TITLE
Going forward: Terminology

### ISSUE THREAD

**Issue by AprilSylph** [new-xkit/x8#3]
While the terminology of "XKit extensions" is familiar to XKit users, having to ever specify the difference between browser extensions and XKit extensions is something that can be avoided. I think the most unambiguous term going forward would be "XKit applets", so as to never confuse between the concepts of browser extensions and XKit features.

**Comment by Wolvan** [comment]
You are right, extension and extension can get really complicated and I agree with using a different name. Not sure why but applets sounds weird to me. How about Plugins? Or maybe to XKit Feature, since on its own XKit doesn't (isn't supposed) to do much except serve as a framework to hook into.

Feature would make it clear that you can add additionally functionality

**Comment by AprilSylph** [comment]
i think "feature" is too loose a term to use here. applied to a current XKit extension, One-Click Postage would be a feature with several subfeatures, such as AlreadyReblogged and Quick Tags support. I'd rather just talk about extensions'/applets'/plugins' features and just call them features.

"XKit Plugins" i can support more when thinking purely about XKit, but using that would recreate the problem of using existing browser terminology. we don't provide browser plugins, so we should avoid the term plugins, as we should avoid the term extensions, since they're not shipped as (individual) browser extensions.

**Comment by Wolvan** [comment]
I can see your concern, yes. I guess nowadays everything is called an App already, so how about we just go with "XKit App" then

**Comment by AprilSylph** [comment]
i would also have suggested "app", but when considering how much people want an XKit app for iOS, avoiding that term also seems necessary to me. and thus i arrived at "applet", since it's not a very common term for anything else, and reflects the fact that XKit extensions are small, specific applications

**Comment by Wolvan** [comment]
I guess you're right. Applet just keeps reminding me of Java

**Comment by AprilSylph** [comment]
that's true... at least java applets are deprecated though

**Comment by nightpool** [comment]
scripts?

**Comment by AprilSylph** [comment]
just calling them scripts doesn't seem as friendly to end users (or at least those that arent familiar with any other userscript addons)

**Comment by Wolvan** [comment]
Yeah I share April's concerns here. Scripts sounds very developer focused, which it shouldn't be.

**Comment by nightpool** [comment]
I would say calling them applets is just as confusing though—either the
user doesn't have any prior associations with the term, in which case it's
semantically neutral, or they do, in which case script is less confusing
then applet.
